title: "Jesita Wida Ajani"
email: jesita.ajani@bsg.ox.ac.uk
github_username: jesitaajani

logo: /assets/images/profile.jpeg
cv_url: /assets/files/CV_2026.pdf

baseurl: ""
url: "https://jesitaajani.github.io"

# SEO Settings
name: "Jesita Wida Ajani"
description: "DPhil candidate in Public Policy at the University of Oxford. Research interests in development, labor, gender, and political economy."

author:
  name: "Jesita Wida Ajani"
  email: "jesita.ajani@bsg.ox.ac.uk"

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude common unneeded files
exclude:
  - .DS_Store
  - Gemfile
  - Gemfile.lock
